# Generated by Django 4.1.5 on 2023-04-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='amazonuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone'),
        ),
    ]
