# Generated by Django 4.1.5 on 2023-04-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_package_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
