# Generated by Django 4.1.5 on 2023-04-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='tid',
            new_name='truct_id',
        ),
    ]
