# Generated by Django 4.1.5 on 2023-04-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_tid_package_truct_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='package',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
