# Generated by Django 4.1.5 on 2023-04-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
    ]
