# Generated by Django 4.1.5 on 2023-04-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_order_is_packed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
