# Generated by Django 4.1.5 on 2023-04-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_product_num_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
