# Generated by Django 4.1.5 on 2023-04-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_order_is_arrived_order_is_delivered_order_is_loaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_arrived',
            new_name='is_truck_arrived',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='truct_id',
            new_name='truck_id',
        ),
        migrations.AddField(
            model_name='amazonuser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
    ]
