# Generated by Django 4.1.5 on 2023-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_is_arrived_order_is_truck_arrived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_truck_requested',
            field=models.BooleanField(default=False),
        ),
    ]
