# Generated by Django 4.1.5 on 2023-04-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_order_is_truck_requested'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
