# Generated by Django 4.1.5 on 2023-04-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_truck_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
